version: "3.9"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: family_doc
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/postgresql/data
    container_name: postgres_db
    ports:
      - '5433:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    volumes:
      - .:/family_doc
    ports:
      - 8000:8000
    image: app:family_doc
    container_name: family_doc_container
    command:  python manage.py runserver 0.0.0.0:8000
    depends_on:
      db:
        condition: service_healthy
