# Generated by Django 4.0.2 on 2022-02-12 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0002_weatherinformation_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weatherinformation",
            name="date",
            field=models.CharField(max_length=200),
        ),
    ]
