# Generated by Django 4.0.2 on 2022-02-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_alter_weatherinformation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherinformation',
            name='country_code',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
